var searchData=
[
  ['iargbasecontainer_2210',['IArgBaseContainer',['../interface_zero_install_1_1_model_1_1_i_arg_base_container.html',1,'ZeroInstall::Model']]],
  ['ibindingcontainer_2211',['IBindingContainer',['../interface_zero_install_1_1_model_1_1_i_binding_container.html',1,'ZeroInstall::Model']]],
  ['icatalogmanager_2212',['ICatalogManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_catalog_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['icategoryintegrationmanager_2213',['ICategoryIntegrationManager',['../interface_zero_install_1_1_desktop_integration_1_1_i_category_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['ichangenotify_2214',['IChangeNotify',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_change_notify.html',1,'NanoByte::Common']]],
  ['iclisubcommand_2215',['ICliSubCommand',['../interface_zero_install_1_1_commands_1_1_i_cli_sub_command.html',1,'ZeroInstall::Commands']]],
  ['icloneable_2216',['ICloneable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20accesspoint_20_3e_2217',['ICloneable&lt; AccessPoint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20accesspointlist_20_3e_2218',['ICloneable&lt; AccessPointList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20appentry_20_3e_2219',['ICloneable&lt; AppEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20applist_20_3e_2220',['ICloneable&lt; AppList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20arg_20_3e_2221',['ICloneable&lt; Arg &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20argbase_20_3e_2222',['ICloneable&lt; ArgBase &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20autoplayevent_20_3e_2223',['ICloneable&lt; AutoPlayEvent &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20binding_20_3e_2224',['ICloneable&lt; Binding &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20capability_20_3e_2225',['ICloneable&lt; Capability &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20capabilitylist_20_3e_2226',['ICloneable&lt; CapabilityList &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20catalog_20_3e_2227',['ICloneable&lt; Catalog &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20category_20_3e_2228',['ICloneable&lt; Category &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20command_20_3e_2229',['ICloneable&lt; Command &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20config_20_3e_2230',['ICloneable&lt; Config &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20constraint_20_3e_2231',['ICloneable&lt; Constraint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20dependency_20_3e_2232',['ICloneable&lt; Dependency &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20domain_20_3e_2233',['ICloneable&lt; Domain &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20element_20_3e_2234',['ICloneable&lt; Element &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20entrypoint_20_3e_2235',['ICloneable&lt; EntryPoint &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feed_20_3e_2236',['ICloneable&lt; Feed &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feedpreferences_20_3e_2237',['ICloneable&lt; FeedPreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20feedreference_20_3e_2238',['ICloneable&lt; FeedReference &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20filetypeextension_20_3e_2239',['ICloneable&lt; FileTypeExtension &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20icon_20_3e_2240',['ICloneable&lt; Icon &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20implementationpreferences_20_3e_2241',['ICloneable&lt; ImplementationPreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20implementationselection_20_3e_2242',['ICloneable&lt; ImplementationSelection &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20interfacepreferences_20_3e_2243',['ICloneable&lt; InterfacePreferences &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20interfacereference_20_3e_2244',['ICloneable&lt; InterfaceReference &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20irecipestep_20_3e_2245',['ICloneable&lt; IRecipeStep &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20key_20_3e_2246',['ICloneable&lt; Key &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20knownprotocolprefix_20_3e_2247',['ICloneable&lt; KnownProtocolPrefix &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20localizablestring_20_3e_2248',['ICloneable&lt; LocalizableString &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20localizablestringcollection_20_3e_2249',['ICloneable&lt; LocalizableStringCollection &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20requirements_20_3e_2250',['ICloneable&lt; Requirements &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20restriction_20_3e_2251',['ICloneable&lt; Restriction &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20retrievalmethod_20_3e_2252',['ICloneable&lt; RetrievalMethod &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20selections_20_3e_2253',['ICloneable&lt; Selections &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20trustdb_20_3e_2254',['ICloneable&lt; TrustDB &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20verb_20_3e_2255',['ICloneable&lt; Verb &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20workingdir_20_3e_2256',['ICloneable&lt; WorkingDir &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'NanoByte::Common']]],
  ['icloneable_3c_20xmldictionary_20_3e_2257',['ICloneable&lt; XmlDictionary &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icloneable_3c_20xmldictionaryentry_20_3e_2258',['ICloneable&lt; XmlDictionaryEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_cloneable.html',1,'']]],
  ['icommandexecutor_2259',['ICommandExecutor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_executor.html',1,'NanoByte::Common::Undo']]],
  ['icommandhandler_2260',['ICommandHandler',['../interface_zero_install_1_1_commands_1_1_i_command_handler.html',1,'ZeroInstall::Commands']]],
  ['icommandmanager_2261',['ICommandManager',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_command_manager.html',1,'NanoByte::Common::Undo']]],
  ['icon_2262',['Icon',['../class_zero_install_1_1_model_1_1_icon.html',1,'ZeroInstall::Model']]],
  ['iconaccesspoint_2263',['IconAccessPoint',['../class_zero_install_1_1_desktop_integration_1_1_access_points_1_1_icon_access_point.html',1,'ZeroInstall::DesktopIntegration::AccessPoints']]],
  ['iconcapability_2264',['IconCapability',['../class_zero_install_1_1_model_1_1_capabilities_1_1_icon_capability.html',1,'ZeroInstall::Model::Capabilities']]],
  ['iconcapabilitymodel_2265',['IconCapabilityModel',['../class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_icon_capability_model.html',1,'ZeroInstall::DesktopIntegration::ViewModel']]],
  ['iconextensions_2266',['IconExtensions',['../class_zero_install_1_1_model_1_1_icon_extensions.html',1,'ZeroInstall::Model']]],
  ['iconmimetypeconverter_2267',['IconMimeTypeConverter',['../class_zero_install_1_1_model_1_1_design_1_1_icon_mime_type_converter.html',1,'ZeroInstall::Model::Design']]],
  ['iconstore_2268',['IconStore',['../class_zero_install_1_1_store_1_1_icon_store.html',1,'ZeroInstall::Store']]],
  ['icontextmenu_2269',['IContextMenu',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_context_menu.html',1,'NanoByte::Common::Controls']]],
  ['icredentialprovider_2270',['ICredentialProvider',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_net_1_1_i_credential_provider.html',1,'NanoByte::Common::Net']]],
  ['idependencycontainer_2271',['IDependencyContainer',['../interface_zero_install_1_1_model_1_1_i_dependency_container.html',1,'ZeroInstall::Model']]],
  ['idescriptioncontainer_2272',['IDescriptionContainer',['../interface_zero_install_1_1_model_1_1_i_description_container.html',1,'ZeroInstall::Model']]],
  ['ieditordialog_2273',['IEditorDialog',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_editor_dialog.html',1,'NanoByte::Common::Controls']]],
  ['ielementcontainer_2274',['IElementContainer',['../interface_zero_install_1_1_model_1_1_i_element_container.html',1,'ZeroInstall::Model']]],
  ['ienvironmentbuilder_2275',['IEnvironmentBuilder',['../interface_zero_install_1_1_services_1_1_executors_1_1_i_environment_builder.html',1,'ZeroInstall::Services::Executors']]],
  ['iexecutor_2276',['IExecutor',['../interface_zero_install_1_1_services_1_1_executors_1_1_i_executor.html',1,'ZeroInstall::Services::Executors']]],
  ['ifeedcache_2277',['IFeedCache',['../interface_zero_install_1_1_store_1_1_feeds_1_1_i_feed_cache.html',1,'ZeroInstall::Store::Feeds']]],
  ['ifeedmanager_2278',['IFeedManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_feed_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['ifetcher_2279',['IFetcher',['../interface_zero_install_1_1_services_1_1_fetchers_1_1_i_fetcher.html',1,'ZeroInstall::Services::Fetchers']]],
  ['ifingerprintcontainer_2280',['IFingerprintContainer',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_fingerprint_container.html',1,'ZeroInstall::Store::Trust']]],
  ['ihighlightcolor_2281',['IHighlightColor',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_highlight_color.html',1,'NanoByte::Common::Controls']]],
  ['iiconcontainer_2282',['IIconContainer',['../interface_zero_install_1_1_model_1_1_i_icon_container.html',1,'ZeroInstall.Model.IIconContainer'],['../interface_zero_install_1_1_publish_1_1_entry_points_1_1_i_icon_container.html',1,'ZeroInstall.Publish.EntryPoints.IIconContainer']]],
  ['iiconstore_2283',['IIconStore',['../interface_zero_install_1_1_store_1_1_i_icon_store.html',1,'ZeroInstall::Store']]],
  ['iimplementationstore_2284',['IImplementationStore',['../interface_zero_install_1_1_store_1_1_implementations_1_1_i_implementation_store.html',1,'ZeroInstall::Store::Implementations']]],
  ['iintegrationmanager_2285',['IIntegrationManager',['../interface_zero_install_1_1_desktop_integration_1_1_i_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['iinterfaceuri_2286',['IInterfaceUri',['../interface_zero_install_1_1_model_1_1_i_interface_uri.html',1,'ZeroInstall::Model']]],
  ['iinterfaceuribindingcontainer_2287',['IInterfaceUriBindingContainer',['../interface_zero_install_1_1_model_1_1_i_interface_uri_binding_container.html',1,'ZeroInstall::Model']]],
  ['ikeyidcontainer_2288',['IKeyIDContainer',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_key_i_d_container.html',1,'ZeroInstall::Store::Trust']]],
  ['imagedatadirectory_2289',['ImageDataDirectory',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_data_directory.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imagedosheader_2290',['ImageDosHeader',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_dos_header.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imagefileheader_2291',['ImageFileHeader',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_file_header.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imageoptionalheader32_2292',['ImageOptionalHeader32',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_optional_header32.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imageoptionalheader64_2293',['ImageOptionalHeader64',['../struct_zero_install_1_1_publish_1_1_entry_points_1_1_image_optional_header64.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['imergeable_2294',['IMergeable',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['imergeable_3c_20appentry_20_3e_2295',['IMergeable&lt; AppEntry &gt;',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_dispatch_1_1_i_mergeable.html',1,'NanoByte::Common::Dispatch']]],
  ['implementation_2296',['Implementation',['../class_zero_install_1_1_model_1_1_implementation.html',1,'ZeroInstall::Model']]],
  ['implementationalreadyinstoreexception_2297',['ImplementationAlreadyInStoreException',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_already_in_store_exception.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationbase_2298',['ImplementationBase',['../class_zero_install_1_1_model_1_1_implementation_base.html',1,'ZeroInstall::Model']]],
  ['implementationnode_2299',['ImplementationNode',['../class_zero_install_1_1_store_1_1_view_model_1_1_implementation_node.html',1,'ZeroInstall::Store::ViewModel']]],
  ['implementationnotfoundexception_2300',['ImplementationNotFoundException',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_not_found_exception.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationpreferences_2301',['ImplementationPreferences',['../class_zero_install_1_1_model_1_1_preferences_1_1_implementation_preferences.html',1,'ZeroInstall::Model::Preferences']]],
  ['implementationselection_2302',['ImplementationSelection',['../class_zero_install_1_1_model_1_1_selection_1_1_implementation_selection.html',1,'ZeroInstall::Model::Selection']]],
  ['implementationstores_2303',['ImplementationStores',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_stores.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationstoreutils_2304',['ImplementationStoreUtils',['../class_zero_install_1_1_store_1_1_implementations_1_1_implementation_store_utils.html',1,'ZeroInstall::Store::Implementations']]],
  ['implementationutils_2305',['ImplementationUtils',['../class_zero_install_1_1_publish_1_1_implementation_utils.html',1,'ZeroInstall::Publish']]],
  ['implementationversion_2306',['ImplementationVersion',['../class_zero_install_1_1_model_1_1_implementation_version.html',1,'ZeroInstall::Model']]],
  ['import_2307',['Import',['../class_zero_install_1_1_commands_1_1_basic_1_1_import.html',1,'ZeroInstall::Commands::Basic']]],
  ['importapps_2308',['ImportApps',['../class_zero_install_1_1_commands_1_1_desktop_1_1_import_apps.html',1,'ZeroInstall::Commands::Desktop']]],
  ['inamed_2309',['INamed',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_i_named.html',1,'NanoByte::Common']]],
  ['inputbox_2310',['InputBox',['https://common.nano-byte.net/class_nano_byte_1_1_common_1_1_controls_1_1_input_box.html',1,'NanoByte::Common::Controls']]],
  ['installcommands_2311',['InstallCommands',['../struct_zero_install_1_1_model_1_1_capabilities_1_1_install_commands.html',1,'ZeroInstall::Model::Capabilities']]],
  ['installcommandsconverter_2312',['InstallCommandsConverter',['../class_zero_install_1_1_model_1_1_design_1_1_install_commands_converter.html',1,'ZeroInstall::Model::Design']]],
  ['integrateapp_2313',['IntegrateApp',['../class_zero_install_1_1_commands_1_1_desktop_1_1_integrate_app.html',1,'ZeroInstall::Commands::Desktop']]],
  ['integrationcommand_2314',['IntegrationCommand',['../class_zero_install_1_1_commands_1_1_desktop_1_1_integration_command.html',1,'ZeroInstall::Commands::Desktop']]],
  ['integrationmanager_2315',['IntegrationManager',['../class_zero_install_1_1_desktop_integration_1_1_integration_manager.html',1,'ZeroInstall::DesktopIntegration']]],
  ['integrationmanagerbase_2316',['IntegrationManagerBase',['../class_zero_install_1_1_desktop_integration_1_1_integration_manager_base.html',1,'ZeroInstall::DesktopIntegration']]],
  ['integrationstate_2317',['IntegrationState',['../class_zero_install_1_1_desktop_integration_1_1_view_model_1_1_integration_state.html',1,'ZeroInstall::DesktopIntegration::ViewModel']]],
  ['interfacepreferences_2318',['InterfacePreferences',['../class_zero_install_1_1_model_1_1_preferences_1_1_interface_preferences.html',1,'ZeroInstall::Model::Preferences']]],
  ['interfacereference_2319',['InterfaceReference',['../class_zero_install_1_1_model_1_1_interface_reference.html',1,'ZeroInstall::Model']]],
  ['interpretedscript_2320',['InterpretedScript',['../class_zero_install_1_1_publish_1_1_entry_points_1_1_interpreted_script.html',1,'ZeroInstall::Publish::EntryPoints']]],
  ['iopenpgp_2321',['IOpenPgp',['../interface_zero_install_1_1_store_1_1_trust_1_1_i_open_pgp.html',1,'ZeroInstall::Store::Trust']]],
  ['ipackagemanager_2322',['IPackageManager',['../interface_zero_install_1_1_services_1_1_native_1_1_i_package_manager.html',1,'ZeroInstall::Services::Native']]],
  ['ipropertystore_2323',['IPropertyStore',['../interface_zero_install_1_1_desktop_integration_1_1_windows_1_1_shortcut_1_1_i_property_store.html',1,'ZeroInstall::DesktopIntegration::Windows::Shortcut']]],
  ['irecipestep_2324',['IRecipeStep',['../interface_zero_install_1_1_model_1_1_i_recipe_step.html',1,'ZeroInstall::Model']]],
  ['iselectioncandidateprovider_2325',['ISelectionCandidateProvider',['../interface_zero_install_1_1_services_1_1_solvers_1_1_i_selection_candidate_provider.html',1,'ZeroInstall::Services::Solvers']]],
  ['iselectionsmanager_2326',['ISelectionsManager',['../interface_zero_install_1_1_services_1_1_i_selections_manager.html',1,'ZeroInstall::Services']]],
  ['ishelllink_2327',['IShellLink',['../interface_zero_install_1_1_desktop_integration_1_1_windows_1_1_shortcut_1_1_i_shell_link.html',1,'ZeroInstall::DesktopIntegration::Windows::Shortcut']]],
  ['isolver_2328',['ISolver',['../interface_zero_install_1_1_services_1_1_solvers_1_1_i_solver.html',1,'ZeroInstall::Services::Solvers']]],
  ['isummarycontainer_2329',['ISummaryContainer',['../interface_zero_install_1_1_model_1_1_i_summary_container.html',1,'ZeroInstall::Model']]],
  ['itask_2330',['ITask',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task.html',1,'NanoByte::Common::Tasks']]],
  ['itaskhandler_2331',['ITaskHandler',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_tasks_1_1_i_task_handler.html',1,'NanoByte::Common::Tasks']]],
  ['itouchcontrol_2332',['ITouchControl',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_touch_control.html',1,'NanoByte::Common::Controls']]],
  ['itrustmanager_2333',['ITrustManager',['../interface_zero_install_1_1_services_1_1_feeds_1_1_i_trust_manager.html',1,'ZeroInstall::Services::Feeds']]],
  ['iundocommand_2334',['IUndoCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_undo_command.html',1,'NanoByte::Common::Undo']]],
  ['ivaluecommand_2335',['IValueCommand',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_undo_1_1_i_value_command.html',1,'NanoByte::Common::Undo']]],
  ['iwizardpage_2336',['IWizardPage',['https://common.nano-byte.net/interface_nano_byte_1_1_common_1_1_controls_1_1_i_wizard_page.html',1,'NanoByte::Common::Controls']]]
];
